// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIDemo.Data;

#nullable disable

namespace WebAPIDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231219105302_AddDescriptionToShirt")]
    partial class AddDescriptionToShirt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDemo.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "My Brand",
                            Color = "Blue",
                            Gender = "Man",
                            Price = 30.0,
                            Size = 10
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "My Brand1",
                            Color = "Blue1",
                            Gender = "Man1",
                            Price = 130.0,
                            Size = 110
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "My Brand2",
                            Color = "Blue2",
                            Gender = "Man2",
                            Price = 230.0,
                            Size = 210
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "My Brand3",
                            Color = "Blue3",
                            Gender = "Man3",
                            Price = 330.0,
                            Size = 310
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
